#!perl

use strict;
use warnings;

use Devel::Platform::Info;
use JSON::PP;

print JSON::PP->new->pretty->canonical->encode(
    Devel::Platform::Info->new->get_info);

# ABSTRACT: Print platform information gathered by Devel::Platform::Info
# PODNAME:
