#!perl

require Data::Dumper;
require Devel::Platform::Info;

print Data::Dumper::Dumper(Devel::Platform::Info->new->get_info);

# ABSTRACT: Print platform information gathered by Devel::Platform::Info
# PODNAME:
